FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
COPY . ./

RUN dotnet --info
RUN dotnet restore src/DevIO.Microservice
RUN dotnet publish src/DevIO.Microservice -c Release -o out
 
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out . 

ENTRYPOINT ["dotnet", "DevIO.Microservice.dll"]